version: '3.7'

volumes: 
  data_banco:


services:
  postgres:
    image: postgres:15
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=megasenhadificil
    volumes:
      - data_banco:/var/lib/postgresql/data
    networks: 
      - default